version: '3'
services:
  blog:
    image: ghost:latest
    working_dir: /var/lib/ghost/current
    ports: 
      - 2368:2368
    volumes: 
      - .:/var/lib/ghost/content/themes/ghost-theme
      - ./ghost-data:/var/lib/ghost/content
    environment: 
      - NODE_ENV=development
    command: >
      bash -c "rm -rf node_modules && bash /usr/local/bin/docker-entrypoint.sh node /var/lib/ghost/current/index.js"