version: '3'
services:
  blog:
    image: ghost:3
    # working_dir: /var/lib/ghost
    ports: 
      - 2368:2368
    volumes: 
      - .:/var/lib/ghost/content/themes/ghost-theme
      - ../ghost-data:/var/lib/ghost/content
    environment: 
      - NODE_ENV=development
    command: >
      bash -c "bash /usr/local/bin/docker-entrypoint.sh node current/index.js"
  watch:
    image: node:lts-buster-slim
    working_dir: /app
    volumes: 
      - .:/app
    environment: 
      - NODE_ENV=development
    command: >
      bash -c "yarn && yarn dev"
